# -*- coding: utf-8 -*-
"""Student Portal Modularized

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qrdcbq6WpssY5viDX2pONbKmDtMXID3V
"""

from datetime import date, timedelta
import random

student_record = {
    "101": {
        "name": "student1",
        "marks": {"CALCULAS": 60, "PHYSICS": 70, "ENGLISH": 80, "PYTHON": 90},
        "present_day": {"CALCULAS": 60, "PHYSICS": 85, "ENGLISH": 95, "PYTHON": 90},
        "absent_day": {"CALCULAS": 40, "PHYSICS": 15, "ENGLISH": 5, "PYTHON": 10},
        "procter": "ramraj"
    },
    "102": {
        "name": "student2",
        "marks": {"CALCULAS": 60, "PHYSICS": 70, "ENGLISH": 80, "PYTHON": 90},
        "present_day": {"CALCULAS": 60, "PHYSICS": 70, "ENGLISH": 80, "PYTHON": 90},
        "absent_day": {"CALCULAS": 40, "PHYSICS": 30, "ENGLISH": 20, "PYTHON": 10},
        "procter": "sitaram"
    }
}

def captcha_verification():
    captcha_generate = random.randrange(1000, 9999)
    print(f"CAPTCHA---{captcha_generate}")

    captcha = int(input("ENTER THE CAPTCHA----"))

    return captcha == captcha_generate

def get_day_name(choice, current_named, current_roll_number):

    def display_menu():
        print("_ _ _ _ --ENTER YOUR CHOICE-- _ _ _ _ ")
        print("< ENTER <1> FOR VIEWING YOUR ATTENDENCE >")
        print("< ENTER <2> FOR VIEWING YOUR MARKS >")
        print("< ENTER <3> FOR YOUR LEAVE PROCESS >")
        print("< ENTER <4> FOR EXIT >")
        print("<ENTER ANYTHING FOR EXIT THE PORTAL1")
        print("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ")

    match choice:
        case 1:
            print("\n_ _ ATTENDENCE PORTAL FOR CURRENT SEMESTER_ _ ")
            present_day = student_record[current_roll_number]["present_day"]
            absent_day = student_record[current_roll_number]["absent_day"]
            attendence = {}

            for subject_key in present_day:
                total_days = present_day[subject_key] + absent_day[subject_key]
                if total_days > 0:
                    attendence[subject_key] = ((present_day[subject_key]) * 100 / total_days)

            print("ATTENDENCE PERCENTAGE PER SUBJECT")
            for key, value in attendence.items():
                print(f"{key} : {value:.2f}%")

            option = int(input("IF YOU WANT TO SEE TOTAL PRESENT AND ABSENT DAYS ENTER <44> IF NOT ENTER ANY INTEGERS :"))

            if option == 44:
                print("TOTAL PRESENT DAYS PER SUBJECT")
                print(present_day)
                print("TOTAL ABSENT DAYS PER SUBJECT")
                print(absent_day)

            print("TO GO BACK TO HOME PAGE PRESS KEY <1> :")
            b = int(input())

            if b == 1:
                display_menu()
                choice = int(input("enter your choice :"))
                get_day_name(choice, current_named, current_roll_number)

        case 2:
            print("\n_ _ MARKS PORTAL FOR CURRENT SEMESTER_ _ ")
            for key, value in student_record[current_roll_number]["marks"].items():
                print(f"{key} : {value}")

            print("TO GO BACK TO HOME PAGE PRESS KEY <1>  :")
            b = int(input())

            if b == 1:
                display_menu()
                choice = int(input("enter your choice :"))
                get_day_name(choice, current_named, current_roll_number)

        case 3:
            print("\n_ _ WELCOME TO LEAVE REQUEST PORTAL_ _ ")
            procter_input = input("ENTER YOUR PROCTER NAME : ").lower().strip()
            stored_procter = student_record[current_roll_number]["procter"].lower()

            if procter_input == stored_procter:
                print("HELLOW I AM YOUR PROCTER I HOPE YOU KNOW ABOUT LEAVE CRIERTRIA")
                reason = input("ENTER REASON FOR YOUR LEAVE :")
                outing = True

                if outing:
                    def count_leave_days(start_date_str, end_date_str):
                        print("ERITE DATE IN (2025-12-29) FORMAT")
                        start_date = date.fromisoformat(start_date_str)
                        end_date = date.fromisoformat(end_date_str)

                        leave_days = 0
                        current_date = start_date

                        while current_date <= end_date:
                            day_of_week = current_date.weekday()
                            if day_of_week < 5:
                                leave_days += 1
                            current_date += timedelta(days=1)
                        return leave_days

                    start = input("ENTER START DATE (YYYY-MM-DD):")
                    end = input("ENTER END DATE (YYYY-MM-DD):")
                    total_leave = count_leave_days(start, end)

                    print(f"Total academic leave days: {total_leave}")

                    if total_leave == 0:
                        print("It's your weekend. Your leave is approved.")
                    else:
                        present_day = student_record[current_roll_number]["present_day"]
                        absent_day = student_record[current_roll_number]["absent_day"]
                        attendence = {}

                        for subject_key in present_day:
                            total_days = present_day[subject_key] + absent_day[subject_key]
                            if total_days > 0:
                                attendence[subject_key] = ((present_day[subject_key]) * 100 / total_days)
                            else:
                                attendence[subject_key] = 100

                        counter = 0

                        print("Current Attendance Percentages:")
                        for value in attendence.values():
                            print(f"{value:.2f}%")
                            if value < 75:
                                counter = counter + 1
                                break

                        if counter != 0:
                            print("YOUR OVERALL ATTENDENCE IS LESS THAN <75> GO CHEAK IN ATTENDENCE SECTION FOR BRIEFLY")
                            print("YOUR APPLICATION FOR LEAVE IS CANCELLED")
                        else:
                            print("YOUR ATTENDENCE IS GREATER THEN <75>")
                            print("_ _ YOUR LEAVE HAS BEEN APPROVED_ _ ")

                        print("TO GO BACK TO HOME PAGE PRESS KEY <1>  :")
                        b = int(input())

                        if b == 1:
                            display_menu()
                            choice = int(input("enter your choice :"))
                            get_day_name(choice, current_named, current_roll_number)
            else:
                print(" Incorrect proctor name. Try again.")
                get_day_name(3, current_named, current_roll_number)

        case 4:
            print("\n--- STUDENT LOGIN/EXIT ---")
            new_named = input("ENTER YOUR NAME :>")
            new_roll_number = input("ENTER YOUR ROLLNUMBER :>")

            if captcha_verification():
                if new_roll_number in student_record and new_named == student_record[new_roll_number]["name"]:
                    print("_ _ _ _ STUDENT LOGIN VERIFIED_ _ _ _ ")
                    display_menu()
                    choice = int(input("ENTER YOUR CHOICE :"))
                    get_day_name(choice, new_named, new_roll_number)
                else:
                    print("_--_--_STUDENT DETAIL NOT FOUND_--_--_")
                    get_day_name(4, new_named, new_roll_number)
            else:
                print("_--_--_ENTERED WRONG CAPTCHA_--_--_")
                get_day_name(4, new_named, new_roll_number)

        case _:
            print("THANKU FOR VISITING")

print("_ _ _ _ ----WELCOME TO TECHNOLOGY COLLAGE FRESHERS PORTAL---- _ _ _ _ ")
print()
named = input("ENTER YOUR NAME :>")
roll_number = input("ENTER YOUR ROLLNUMBER :>")

if captcha_verification():
    if roll_number in student_record and named == student_record[roll_number]["name"]:
        print("_ _ _ _ STUDENT LOGIN VERIFIED_ _ _ _ ")

        print("< ENTER <1> FOR VIEWING YOUR ATTENDENCE >")
        print("< ENTER <2> FOR VIEWING YOUR MARKS >")
        print("< ENTER <3> FOR YOUR LEAVE PROCESS >")
        print("< ENTER <4> FOR EXIT >")
        print("< ENTER <ANYTHING> FOR EXITING PORTAL >")
        print("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ")

        choice = int(input("ENTER YOUR CHOICE :"))

        get_day_name(choice, named, roll_number)
    else:
        print("_--_--_STUDENT DETAIL NOT FOUND_--_--_")
        get_day_name(4, named, roll_number)
else:
    print("_--_--_ENTERED WRONG CAPTCHA_--_--_ ")
    get_day_name(4, named, roll_number)